# --------------------
[General]
# --------------------

# determines how often the mpc controller is triggered, namely every Nth TRNSYS time step (1=every time step, 4=every 4th time step, and so on)
mpc_trigger = 1
filename_logfile = PythonLog.log


# --------------------
[Weather data]
# --------------------

filename = Windetc20190804.txt
row_offset = 5
col_index_ta = 25
col_index_igs = 26
col_index_ign = 27


# --------------------
[Electricity data]
# --------------------

filename = EXAA_Day_Ahead_Preise_&_CO2-Intensitaet_2015-2022_1_2019.txt
offset = 2
col_index_price = 2
col_index_co2 = 3
factor_price = 0.000001
factor_co2 = 0.001

# --------------------
[Direct signal]
# --------------------

filename = Signal.txt

# --------------------
[Heat pump]
# --------------------

# coefficient of performance (COP) of heat pump for heating
cop = 5

# energy efficiency ratio (EER) of heat pump for cooling
eer = 12

# heat pump modulation step size [W]
mod_step = 100


# --------------------
[Optimizer]
# --------------------

# time step of the prediction [s]
dt_pred = 3600

# termination criterion optimization - change in least square error
optimizer_tolerance = 0.0000005

# True = pass optimizer_tolerance setting to optimizer - False = ignore it
set_optimizer_tolerance = True

# prediction horizon [h]
pred_hor = 12

# cost optimization flag
cost_optimization = True

# gs_criterion
#gs_criterion = COST
#gs_criterion = CO2
gs_criterion = Signal


# Exponents and factors for least square error calculation
alpha_pos = 1.0
alpha_neg = 5.0
beta = 4.1
gamma = 1.3
zeta = 1.0

[Simulation logger]
# %s is a placeholder for the heating zone number
filename = log_values_zone%s.log
trndata_input_varnames = area_BTA [m²], alpha_w [W/m²K], alpha_s [W/m²K], k_heatloss [W/K],
                          cbta [Wh/K], cr [Wh/K], qheizmax [W], qkuehlmax [W], heizperiode [bool],
                          tbtasoll [°C], tzone [°C], tnodeo [°C], Zone
trndata_output_varnames = index, heizperiode [bool], tbtasoll [°C], tzone [°C], tnodeo [°C], Zone,
                           Qheat [W], Costs [€], Emissions [gCO2eq]