[General]

# perturbation value [W]
dHeat = 500

# time step of the prediction [s]
dt_pred = 3600

# max. runs of iteration possible
max_count = 500

# termination criterion optimization - change in least square error
ChgProgTol = 0.000005

# prediction horizon [h]
pred_hor = 48

# determines how often the mpc controller is triggered, namely every Nth TRNSYS time step (1=every time step, 4=every 4th time step, and so on)
mpc_trigger = 1

# coefficient of performance (COP) of heat pump for heating
cop = 5

# energy efficiency ratio (EER) of heat pump for cooling
eer = 12

# cost optimization flag
cost_optimization = True