[General]

# time step of the prediction [s]
dt_pred = 3600

# termination criterion optimization - change in least square error
optimizer_tolerance = 0.0000005

# True = pass optimizer_tolerance setting to optimizer - False = ignore it
set_optimizer_tolerance = True


# prediction horizon [h]
pred_hor = 48

# determines how often the mpc controller is triggered, namely every Nth TRNSYS time step (1=every time step, 4=every 4th time step, and so on)
mpc_trigger = 1

# coefficient of performance (COP) of heat pump for heating
cop = 5

# energy efficiency ratio (EER) of heat pump for cooling
eer = 12

# heat pump modulation step size [W]
heat_pump_mod_step = 100

# cost optimization flag
cost_optimization = True

# price signal
price_signal = COST
#price_signal = CO2

[Optimizer constants]

# Exponents and factors for least square error calculation
alpha_pos = 1.0
alpha_neg = 5.0
beta = 4.0
gamma = 1.3